# repokeeper configuration: https://github.com/vannt-dev/repokeeper
schema: 1
standard: 1.4.1
platform: github
stacks:
  - script
modules:
  editorconfig: true
  commits: true
  hooks: true
  ci: true
  release: true
  deps: true
  gitignore: true
  health:
    license: MIT
    copyright: 2026 Van Nguyen
    contact: https://github.com/vannt-dev
    codeowners:
      - "@vannt-dev"
owned:
  - LICENSE
stack_options: {}
github:
  default_branch: master
